global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'admin-service'
    static_configs:
      - targets: ['host.docker.internal:9091']

  - job_name: 'user-service'
    static_configs:
      - targets: ['host.docker.internal:9092']